### ISSUE TITLE
Can't find File "/github/workspace/clover.xml"

### ISSUE THREAD

**Issue by francescodiperna** [timkrase/phpunit-coverage-badge#11]
Hello, I'm trying to use the action but alway I got the below message.
The clover.xml file is in the root project.
Can anyone cal help me?

Bye

```

Fatal error: Uncaught Assert\InvalidArgumentException: File "/github/workspace/clover.xml" was expected to exist. in /srv/vendor/beberlei/assert/lib/Assert/Assertion.php:2725
Stack trace:
#0 /srv/vendor/beberlei/assert/lib/Assert/Assertion.php(1604): Assert\Assertion::createException('/github/workspa...', 'File "/github/w...', 102, NULL)
#1 /srv/src/Config.php(32): Assert\Assertion::file('/github/workspa...')
#2 /srv/src/WorkflowService.php(26): PhpUnitCoverageBadge\Config->__construct()
#3 /srv/src/entry.php(15): PhpUnitCoverageBadge\WorkflowService->run()
#4 {main}
  thrown in /srv/vendor/beberlei/assert/lib/Assert/Assertion.php on line 2725
```

**Comment by timkrase** [comment]
Sorry for the late response.

Did you make sure to run Github's checkout action before trying to run the action?

**Comment by francescodiperna** [comment]
Good morning, now it is working. Thanks
